### ISSUE TITLE
Nicer readme

### ISSUE THREAD

**Issue by vi4m** [allegro/json-logic-kmp#39]
We can provide a nicer README about the potential usage of this library. 

* what's the purpose of this library
* how to use it
* how to incorporate into typical backend

to grow the adoption of this library :)

**Comment by PaulinaSadowskaAllegro** [comment]
It's definitely on our roadmap - but we want to wait for this library to be more stable so we don't have to change this README that often :) Stay tuned, it'll be added soon :)
